title: "TLC Trip Record Data"
description: "A containerized Spark, Airflow, MinIO (S3) & DuckDB data engineering project using NYC Yellow Taxi Trip Data."
theme: jekyll-theme-cayman

author: "Anass Yarroudh"
show_downloads: false
github:
  is_project_page: true
  repository_url: "https://github.com/Yarroudh/dataengineering"
