backend: "minio"

bucket_name: "de-lake"
endpoint_url: "http://minio:9000"
region: "us-east-1"

paths:
  bronze_prefix: "landing"
  silver_prefix: "prepared"
  duckdb_prefix: "duckdb"

duckdb:
  warehouse_file: "taxi.duckdb"